---
# $pki_dir - /etc/icinga2/pki in the default installation
# $fqdn - fully host+domain name of the client.
# $icinga2_master - resolvable fqdn of the master
# $icinga2_master_port - the port the master is connectable on.
# $ticket - generated on the master via 'icinga2 pki ticket --cn $fqdn'

# mkdir icinga:icinga 0700 $pki_dir
# icinga2 pki new-cert --cn $fqdn --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt
# icinga2 pki save-cert --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt --trustedcert $pki_dir/trusted-master.crt --host $icinga2_master
# icinga2 pki request --host $icinga2_master --port $icinga2_master_port --ticket $ticket --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt --trustedcert $pki_dir/trusted-master.crt --ca $pki_dir/ca.key
# icinga2 node setup --ticket $ticket --endpoint $icinga2_master --zone $fqdn --master_host $icinga2_master --trustedcert $pki_dir/trusted-master.crt
# service icinga2 restart  # or however you restart your icinga


- name: request ticket on master
  shell: icinga2 pki ticket --cn {{ ansible_fqdn }}
  delegate_to: "{{ item }}"
  with_items: groups.icingamaster
  register: ticket

- debug: var=ticket
  with_items: groups.icingamaster

- name: prepare pki directory
  file: path=/etc/icinga2/pki state=directory owner=nagios group=nagios mode=0700

- name: new-cert
  shell: icinga2 pki new-cert --cn {{ ansible_fqdn }} --key /etc/icinga2/pki/{{ ansible_fqdn }}.key --cert /etc/icinga2/pki/{{ ansible_fqdn }}.crt creates=/etc/icinga2/pki/{{ ansible_fqdn }}.crt
  notify: restart icinga2

- name: save-cert
  shell: icinga2 pki save-cert --key /etc/icinga2/pki/{{ ansible_fqdn }}.key --cert /etc/icinga2/pki/{{ ansible_fqdn }}.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --host {{ item }} creates=/etc/icinga2/pki/trusted-master.crt
  with_items: groups.icingamaster
  notify: restart icinga2

- name: pki request
  shell: icinga2 pki request --host {{ item[1] }} --port 5665 --ticket {{ item[0].stdout }} --key /etc/icinga2/pki/{{ ansible_fqdn }}.key --cert /etc/icinga2/pki/{{ ansible_fqdn }}.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --ca /etc/icinga2/pki/ca.key creates=/etc/icinga2/pki/ca.key
  with_nested:
    - ticket.results
    - groups.icingamaster
  notify: restart icinga2

- name: node setup
  shell: icinga2 node setup --ticket {{ item[0].stdout }} --zone {{ ansible_fqdn }} --master_zone {{ item[1] }} --master_host {{ item[1] }} --endpoint {{ item[1] }},{{ item[1] }},5665 --trustedcert /etc/icinga2/pki/trusted-master.crt creates=/etc/icinga2/pki/ca.crt
  with_nested:
    - ticket.results
    - groups.icingamaster
  notify: restart icinga2

- name: add node on master
  shell: icinga2 node add {{ ansible_fqdn }} creates=/etc/icinga2/repository.d/zones/{{ ansible_fqdn }}.conf
  delegate_to: "{{ item }}"
  with_items: groups.icingamaster
  notify: restart master icinga2

- name: enable remote commands
  template: src=api.conf.j2 dest=/etc/icinga2/features-available/api.conf owner=root group=root mode=0644
  notify: restart icinga2

- meta: flush_handlers

- name: node update-config on master
  shell: icinga2 node update-config creates=/etc/icinga2/repository.d/hosts/{{ ansible_fqdn }}/ping4.conf
  delegate_to: "{{ item }}"
  with_items: groups.icingamaster
  notify: restart master icinga2
