---
# Icingaweb2 manual setup steps taken from
# https://github.com/Icinga/icingaweb2/blob/master/doc/installation.md

- name: install required packages
  apt: name={{ item }} state=installed
  with_items:
    - php5-common
    - libapache2-mod-php5
    - php5
    - php-pear
    - php5-cli
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-mysql
    - php5-imagick
    - php5-intl
    - icingaweb2
    - icinga2-ido-mysql
  register: icinstall

- name: enable php module
  shell: php5enmod {{ item }} creates=/etc/php5/apache2/conf.d/20-{{ item }}.ini
  with_items:
    - imagick
    - intl
  notify: restart apache

- name: configure php timezone (mod_php)
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^Listen " insertafter="^;date.timezone " line="date.timezone = Europe/Brussels"
  notify: restart apache

- name: enable ido-mysql and command feature for web
  shell: icinga2 feature enable {{ item }} creates=/etc/icinga2/features-enabled/{{ item }}.conf
  with_items:
    - ido-mysql
    - command
  when: icinstall.changed

- name: create icingaweb2 database
  mysql_db: name={{ webdbname }} state=present
  register: webdb

- name: create icingaweb2 database user
  mysql_user: name={{ webdbuser }} password={{ webdbpass }} priv={{ webdbname }}.*:ALL append_privs=true state=present

- name: load database schema
  mysql_db: state=import name={{ webdbname }} target=/usr/share/icingaweb2/etc/schema/mysql.schema.sql
  when: webdb.changed

- name: create users in database
  command: >
    mysql --user {{ webdbuser }} --password {{ webdbpass }} {{ webdbname }}
    --batch --skip-column-names
    --execute "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('{{ item.name }}', 1, '{{ item.pass }}')"
  with_items: webusers

- name: put configuration templates
  template: src=icingaweb2/{{ item }}.j2 dest=/etc/icingaweb2/{{ item }} owner=root group=root mode=0644
  with_items:
    - authentication.ini
    - config.ini
    - resources.ini
    - roles.ini
