---
- name: install mysql
  apt: name={{ item }} state=latest cache_valid_time=3600 update_cache=yes
  with_items:
    - automysqlbackup
    - mysql-server
    - python-mysqldb
  register: mysqlinstall

- name: put my.cnf template
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: put innodb.cnf template
  template: src=innodb.cnf.j2 dest=/etc/mysql/conf.d/innodb.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: ensure mysql is running
  service: name=mysql state=running enabled=yes

- name: generate random password
  shell: openssl passwd -in /dev/urandom | head -1
  register: mysqlrootpass
  when: mysqlinstall.changed

- name: create rootuser
  mysql_user: name=root host={{ item }} password={{ mysqlrootpass.stdout }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysqlrootpass.changed

- name: save root password for mysql
  template: src=root-my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: mysqlrootpass.changed

- name: configure automysqlbackup
  template: src=automysqlbackup.j2 dest=/etc/default/automysqlbackup
