- name: icinga2 monitored system playbook
  hosts: monitored
  sudo: true

  pre_tasks:
    #- include_vars: "./os_vars/{{ ansible_distribution_release }}.yml"
    #  tags: ['backup','monitoring']
    - apt: update_cache=yes cache_valid_time=3600

  roles:
    - system
    - icinga-satellite
